config/routes.rb
CaptainsBattleship::Application.routes.draw do

  root 'games#new'

  resources :games, :only => ['new', 'show', 'strike', 'create_player_vs_ai', 'create_p45_vs_ai', 'create_p45_vs_player'] do
    member do
      get '/players/:player_id' => 'games#show', as: 'show'
      post '/players/:player_id' => 'games#strike', as: 'strike'
    end

    collection do
      post 'create_player_vs_ai'
      post 'create_p45_vs_ai'
      post 'create_p45_vs_player'
    end
  end

end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id           :integer          not null, primary key
#  player1_id   :integer
#  player2_id   :integer
#  winner_id    :integer
#  next_turn_id :integer
#  status       :string(255)      not null
#  height       :integer          not null
#  width        :integer          not null
#  created_at   :datetime
#  updated_at   :datetime
#

class Game < ActiveRecord::Base
  class AlreadyRequiredNumOfPlayers < StandardError; end
  class PlayerNotReady < StandardError; end
  class InValidStateForStrike < StandardError; end
  class NotYourTurn < StandardError; end

  belongs_to :player1, class_name: '::Player', foreign_key: 'player1_id'
  belongs_to :player2, class_name: '::Player', foreign_key: 'player2_id'
  belongs_to :winner, class_name: '::Player', foreign_key: 'winner_id'
  belongs_to :next_turn, class_name: '::Player', foreign_key: 'next_turn_id'

  before_validation :set_defaults, :on => :create

  DefaultHeight = 10
  DefaultWidth = 10
  Ships = [
    {id: 1, name: 'Carrier', size: 5},
    {id: 2, name: 'Battleship', size: 4},
    {id: 3, name: 'Destroyer', size: 3},
    {id: 4, name: 'Submarines', size: 2},
    {id: 5, name: 'Submarines', size: 2},
    {id: 6, name: 'Patrol Boats', size: 1},
    {id: 7, name: 'Patrol Boats', size: 1}
  ]

  def adds_player!(player)
    raise AlreadyRequiredNumOfPlayers.new if player1.present? && player2.present?

    if self.player1.blank?
      self.player1 = player
    elsif self.player2.blank?
      self.player2 = player
    end

    self.save! and player
  end

  def player_ready(player)
    raise PlayerNotReady.new unless player.ready?
    return if player1.blank? || player2.blank?

    if status == 'initial' && player1.ready? && player2.ready?
      update_attributes!(status: 'ready_to_start', next_turn: player1)
    end
  end

  def strikes_opposing_player(player, x, y)
    raise NotYourTurn.new unless player == next_turn
    raise InValidStateForStrike.new unless playing?
    opponent_of(player).takes_a_hit!(x, y).tap { |result|
      if result[:all_sunk]
        update_attributes!(status: 'finished', next_turn: nil, winner: player)
      else
        next_turn = opponent_of(player)
        update_attributes!(status: 'in_progress', next_turn: next_turn)
      end
    }
  end

  def ships
    Ships
  end

  def playing?
    %w(in_progress ready_to_start).include?(status)
  end

private
  def set_defaults
    self.status = 'initial'
    self.width ||= DefaultWidth
    self.height ||= DefaultHeight
  end

  def opponent_of(player)
    [player1, player2].detect { |x| x != player }
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
  end

  def create_p45_vs_ai
    @player = GameBuilder.build_p45_vs_ai!
    redirect_to show_game_url(id: @player.game, player_id: @player.to_param)
  end

  def create_player_vs_ai
    @player = GameBuilder.build_player_vs_ai!(player_params)
    redirect_to show_game_url(id: @player.game, player_id: @player.to_param)
  end

  def create_p45_vs_player
    @player = GameBuilder.build_p45_vs_player!(player_params)
    redirect_to show_game_url(id: @player.game, player_id: @player.to_param)
  end

  def show
    @player = Player.find(params[:player_id])
    @game = @player.game

    respond_to do |format|
      format.html
      format.js {
        if @game.playing? && @game.next_turn.auto_play?
          @game.next_turn.strikes!
          @game.reload
        end
      }
    end
  end

  def strike
    @player = Player.find(params[:player_id])
    @game = @player.game
    @player.strikes!(coordinate_params[:x].to_i, coordinate_params[:y].to_i)
    @game.reload

    render 'show.js.erb'
  end

private
  def coordinate_params
    params[:coordinate].permit(:x, :y)
  end

  def player_params
    params[:player].permit(:email, :name)
  end
end

app/views/games/_player_details_modal.html.erb
<div id="<%= id %>" class="reveal-modal">
  <h3>Player Detail</h3>

  <%= form_for Players::HumanPlayer.new, url: url, as: 'player' do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>

    <%= f.label :email %>
    <%= f.text_field :email, type: 'email', required: true %>

    <%= f.submit 'Submit', :class => 'button' %>
  <% end %>

  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/games/new.html.erb
<div class='row'>
  <h2 class='subheader text-center'>Game Mode</h2>

  <div class='small-6 columns small-offset-3'>
    <a class="button large round" data-reveal-id="player-vs-ai-modal" style='width:100%;' href="#">Player VS AI Player</a>

    <a class="button large round" data-reveal-id="p45-vs-player-modal" style='width:100%;' href="#">Platform 45 VS Player</a>

    <%= form_tag create_p45_vs_ai_games_url do %>
      <%= submit_tag 'Platform 45 vs AI Player', :class => 'button round expand', style: 'font-size:1.25em' %>
    <% end %>
  </div>
</div>

<%= render 'player_details_modal', id: 'player-vs-ai-modal', url: create_player_vs_ai_games_url %>
<%= render 'player_details_modal', id: 'p45-vs-player-modal', url: create_p45_vs_player_games_url %>

app/views/games/show.html.erb
<h2 class='subheader text-center'>
  <%= @player.game.player1.name %> VS <%= @player.game.player2.name %>
</h2>

<div class='row'>
  <div class='large-9 columns'>
    <h3 class='subheader'><%= @player.name %>'s Radar</h3>

    <%= form_tag strike_game_url(@player.game, @player) do %>
      <%= hidden_field_tag 'coordinate[x]' %>
      <%= hidden_field_tag 'coordinate[y]' %>
      <div data-refresh-strikes='true'>
        <%= render 'games/battlefield/strikes' %>
      </div>
    <% end %>

    <h3 class='subheader'><%= @player.name %>'s Battlefield</h3>
    <div data-refresh-battlefield='true'>
      <%= render 'games/battlefield/battlefield' %>
    </div>
  </div>

  <div class='large-3 columns'>
    <h3 class='subheader'>Next turn</h3>
    <span data-refresh-turn='true'>
      <% if @game.winner.present? %>
        WINNER: <%= @game.winner.name %>
      <% elsif @game.next_turn.present? %>
        <%= @game.next_turn.name %>
      <% end %>
    </span>
  </div>
</div>

<script>
  $(document).ready(function() {
    var polling = function() {
      $.getScript('<%= show_game_url(@player.game, @player, format: 'js') %>', function(data) {
        setTimeout(function(){
          polling();
        }, 3000);
      });
    };

    polling();
  });
</script>

app/views/games/show.js.erb
<% battlefield = render('games/battlefield/battlefield') %>
$('[data-refresh-battlefield=true]').html(<%=raw battlefield.to_json %>);

<% strikes = render('games/battlefield/strikes') %>
$('[data-refresh-strikes=true]').html(<%=raw strikes.to_json %>);

<% if @game.winner.present? %>
  $('[data-refresh-turn=true]').text('WINNER: ' + <%=raw @game.winner.name.to_json %>);
<% elsif @game.next_turn.present? %>
  $('[data-refresh-turn=true]').text(<%=raw @game.next_turn.name.to_json %>);
<% end %>